DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `email` varchar(255) NOT NULL COMMENT 'メール',
  `display_name` varchar(255) NOT NULL COMMENT '表示名',
  `password` varchar(255) NOT NULL COMMENT 'パスワード',
  `sex` char(1) COMMENT '性別(M:男性、F:女性、E:その他）',
  `date_of_birth` date COMMENT '生年月日',
  `grade_id` int(11) NOT NULL COMMENT 'グレードID',
  `prefecture_id` int(11) unsigned COMMENT '都道府県ID',
  `area_id` int(11) unsigned COMMENT 'エリアID',
  `address` varchar(255) COMMENT '住所',
  `name` varchar(255) COMMENT '名前',
  `name_kana` varchar(255) COMMENT 'カタカナ',
  `phone_number` varchar(255) COMMENT '電話番号',
  `image_path` varchar(255) COMMENT 'イメージ',
  `about_me` text COMMENT '自己紹介',
  `settlement_id` bigint unsigned COMMENT '決済情報ID',
  `evaluate_id` bigint unsigned COMMENT '評価ID',
  `is_info_mail` char(1) NOT NULL default 'N' COMMENT '情報メールフラグ(Y:同意、N:拒否)',
  `is_mail_magazine` char(1) NOT NULL default 'N' COMMENT 'メールマガジン受信フラグ(Y:同意、N:拒否)',
  `is_push_alert` char(1) NOT NULL default 'N'  COMMENT 'PUSH許可フラグ(Y:許可、N:拒否)',
  `is_restriction` char(1) NOT NULL default 'N'  COMMENT '利用停止制限フラグ(Y:制限、N:制限なし)',
  `is_mail_certificated` char(1) NOT NULL default 'N'  COMMENT 'メール認証(Y:認証済み、N:未認証)',
  `is_phone_certificated` char(1) NOT NULL default 'N'  COMMENT '電話認証(Y:認証済み、N:未認証)',
  `mail_certificate_date` datetime COMMENT 'メール認証送信日付',
  `phone_certificate_date` datetime COMMENT '電話認証送信日付',
  `recent_login_date` datetime COMMENT '最近ログイン日付',
  `recent_login_ip` varchar(255) COMMENT '最近ログインIP',
  `recent_login_device` varchar(255) COMMENT '最近ログインDevice',
  `recent_login_os_version` varchar(255) COMMENT '最近ログインOS Version',
  `del_flg` char(1) NOT NULL default 'N' COMMENT '削除フラグ(Y:削除済み、N:未削除)',
  `created_at` datetime NOT NULL COMMENT '登録日時',
  `modified_at` datetime NOT NULL COMMENT '更新日時',
  PRIMARY KEY (`id`),
  KEY `ix_gradeid_id` (`grade_id`,`id`)
)