from django.db import models
            

class Shops(models.Model):
    shop_type = models.CharField(max_length=1)
    prefecture_id = models.IntegerField()
    area_id = models.IntegerField()
    address = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    name_kana = models.CharField(max_length=255)
    sub_name = models.CharField(max_length=255)
    display_name = models.CharField(max_length=255)
    manager_name = models.CharField(max_length=255)
    manager_name_kana = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=255)
    mobile_number = models.CharField(max_length=255)
    fax_number = models.CharField(max_length=255)
    main_image_path = models.CharField(max_length=255)
    sub_image_path = models.CharField(max_length=255)
    explain_first = models.TextField()
    explain_second = models.TextField()
    explain_third = models.TextField()
    grade_id = models.IntegerField()
    settlement_id = models.IntegerField()
    rate_average = info_mail_flg = models.CharField(max_length=1)
    mail_magazine_flg = models.CharField(max_length=1)
    push_alert_flg = models.CharField(max_length=1)
    restriction_flg = models.CharField(max_length=1)
    mail_certificated_flg = models.CharField(max_length=1)
    phone_certificated_flg = models.CharField(max_length=1)
    mail_certificate_date = models.DateTimeField()
    phone_certificate_date = models.DateTimeField()
    del_flg = models.CharField(max_length=1)
    created_at = models.DateTimeField()
    modified_at = models.DateTimeField()
                            
    class Meta:
        db_table = 'shops'
